# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf62a04d1953b096793927ad503255f7de714b675c40137928b34107957e769256c77597457ca75f0267e2b06ce6d8128e39e2909af52594e98671cbb8b90d6

test:
  secret_key_base: 885aae8ce37dd8ca6766f18ba1e3874f7e8a9d0bd4204ab76e52660910f03cc08a946abd9c9b837ae3c5b78e22ad97149d8c85b1f8f356175aeeb7270f60b7f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
